In [4]:
import sys
sys.path.append('../..')
import numpy as np
import pandas as pd
from pathlib import Path
from model_utils import split_samples, split_periods
from neuralhydrology.utils.config import Config
import xarray as xr
from tqdm.auto import tqdm
import pickle

In [5]:
import matplotlib.pyplot as plt

## Configuración

In [6]:
# cargar archivo de configuración
config_file = Path('config_HP.yml')
cfg = Config(config_file)

target = cfg.target_variables[0]

print(cfg.experiment_name)
print('epochs:', cfg.epochs, sep='\t\t')
print('hidden size:', cfg.hidden_size, sep='\t')
print('batch size:', cfg.batch_size, sep='\t')
print('dropout:', cfg.output_dropout, sep='\t')
print('clip gradients:', cfg.clip_gradient_norm, sep='\t')

FileNotFoundError: config_HP.yml

## Samples

In [110]:
# load attribute table
attrs = pd.read_csv(cfg.data_dir / 'attributes' / 'attributes_combined.csv', index_col='reservoir_id')
print(attrs.shape)

split_samples(attrs.index.tolist(), cal=.6, val=.2, path=Path('./data'), seed=0)

(291, 7)

## Periods

In [90]:
# define train, validation and tes periods
periods = {}
for file in tqdm((cfg.data_dir / 'time_series').glob('*.nc')):
    df = xr.open_dataset(file)[cfg.target_variables].to_pandas()
    periods[file.stem] = split_periods(df, cal=.6, val=.2)
periods_da = xr.concat([da.assign_coords(id=id) for id, da in periods.items()], dim='id')

# make sure there's 1 year of data before the start date
cutoff_date = np.datetime64('1992-01-02', 'ns')
periods_da = periods_da.where(periods_da >= cutoff_date, other=cutoff_date)
del periods

# reorganize periods as a dictionary
periods_dct = {}
for period in periods_da.period.data:
    periods_dct[period] = {}
    for ID in periods_da.id.data:
        periods_dct[period][ID] = {}
        for date in periods_da.date.data:
            periods_dct[period][ID][f'{date}_dates'] = [pd.Timestamp(periods_da.sel(period=period, id=ID, date=date).to_numpy().item())]

# export as Pickle
for period, dct in periods_dct.items():
    with open(f'./data/periods_{period}.pkl', 'wb') as file:
        pickle.dump(dct, file)

0it [00:00, ?it/s]

***

In [49]:
min_date = pd.Timestamp(1900, 1, 1)
max_date = pd.Timestamp(2100, 1, 1)
for period, ids_dct in periods_dct.items():
    for ID, dates_dct in ids_dct.items():
        min_date = max(min_date, dates_dct['start_dates'][0])
        max_date = min(max_date, dates_dct['end_dates'][0])

In [50]:
min_date, max_date

(Timestamp('2015-04-29 00:00:00'), Timestamp('1993-05-08 00:00:00'))

In [57]:
min_date = pd.Timestamp(1900, 1, 1)
max_date = pd.Timestamp(2100, 1, 1)
for id in periods_da.id.data:
    min_date = max(min_date, periods_da.sel(id=id).min().to_numpy())
    max_date = min(max_date, periods_da.sel(id=id).max().to_numpy())
min_date, max_date

(array('2011-09-13T00:00:00.000000000', dtype='datetime64[ns]'),
 array('2006-09-30T00:00:00.000000000', dtype='datetime64[ns]'))

In [93]:
periods_da.sel(id='2511').to_pandas()

period      train validation       test
date
start  2007-11-19 2002-06-11 1997-01-01
end    2024-03-12 2007-11-18 2002-06-10

In [81]:
periods_da.sel(id=2511).to_pandas()

period      train validation       test
date
start  2007-11-19 2002-06-11 1997-01-01
end    2024-03-12 2007-11-18 2002-06-10

In [82]:
periods_da.sel(id=2536).to_pandas()

period      train validation       test
date
start  2002-04-22 1996-02-26 1992-01-02
end    2020-09-30 2002-04-21 1996-02-25

***

In [67]:
PATH_RESOPS = Path('./data/ResOpsES')

In [68]:
ID = 2511

In [71]:
cfg.dynamic_inputs

['inflow_efas5', 'evaporation_emo1']

In [72]:
cfg.target_variables

['volume']

In [84]:
with open('./data/periods_train.pkl', 'rb') as file:
    periods_train = pickle.load(file)

In [85]:
periods_train

{10: {'start_dates': [Timestamp('2003-09-13 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1019: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1026: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1033: {'start_dates': [Timestamp('2006-08-09 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1038: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1047: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1062: {'start_dates': [Timestamp('2009-07-14 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1064: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1065: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1066: {'start_dates': [Timestamp('2007-11-19 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1068: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1070: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1075: {'start_dates': [Timestamp('2007-11-19 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1078: {'start_dates': [Timestamp('2007-11-19 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1083: {'start_dates': [Timestamp('2006-05-10 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1089: {'start_dates': [Timestamp('2003-11-03 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1091: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 110: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1125: {'start_dates': [Timestamp('2006-05-10 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1145: {'start_dates': [Timestamp('2003-07-23 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1146: {'start_dates': [Timestamp('2009-07-14 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1156: {'start_dates': [Timestamp('2000-10-31 00:00:00')],
  'end_dates': [Timestamp('2017-01-24 00:00:00')]},
 116: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1165: {'start_dates': [Timestamp('2010-10-06 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1167: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1172: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1188: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1197: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1198: {'start_dates': [Timestamp('2003-07-23 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1199: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1226: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1255: {'start_dates': [Timestamp('2007-11-19 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1257: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 126: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1272: {'start_dates': [Timestamp('2008-12-05 00:00:00')],
  'end_dates': [Timestamp('2024-03-10 00:00:00')]},
 1285: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1290: {'start_dates': [Timestamp('2014-01-06 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1306: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 132: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1321: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1324: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1333: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1336: {'start_dates': [Timestamp('2008-10-04 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1339: {'start_dates': [Timestamp('1997-11-26 00:00:00')],
  'end_dates': [Timestamp('2009-09-30 00:00:00')]},
 1342: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1364: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1367: {'start_dates': [Timestamp('2013-12-15 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1378: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1395: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1421: {'start_dates': [Timestamp('2006-05-10 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 143: {'start_dates': [Timestamp('2012-12-16 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1445: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1450: {'start_dates': [Timestamp('2015-04-29 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1455: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1462: {'start_dates': [Timestamp('2006-05-10 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1463: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1485: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1494: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1502: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 151: {'start_dates': [Timestamp('2014-05-11 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1525: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 153: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1544: {'start_dates': [Timestamp('2005-12-16 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1558: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1564: {'start_dates': [Timestamp('2000-04-22 00:00:00')],
  'end_dates': [Timestamp('2015-10-01 00:00:00')]},
 1565: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1579: {'start_dates': [Timestamp('2005-12-16 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1590: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 160: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1611: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1640: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1643: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1645: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1649: {'start_dates': [Timestamp('1998-04-21 00:00:00')],
  'end_dates': [Timestamp('2010-09-30 00:00:00')]},
 165: {'start_dates': [Timestamp('2009-07-14 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1657: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1665: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1673: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1674: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1698: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1699: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 171: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1727: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 173: {'start_dates': [Timestamp('2013-02-25 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1730: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 174: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1767: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1771: {'start_dates': [Timestamp('2009-01-21 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1773: {'start_dates': [Timestamp('1996-09-14 00:00:00')],
  'end_dates': [Timestamp('2006-09-30 00:00:00')]},
 1786: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 179: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1796: {'start_dates': [Timestamp('2004-11-26 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1803: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1807: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1808: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1828: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1829: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 183: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1840: {'start_dates': [Timestamp('2009-08-09 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1880: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1887: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1895: {'start_dates': [Timestamp('2007-12-02 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1898: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1902: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1904: {'start_dates': [Timestamp('1996-09-14 00:00:00')],
  'end_dates': [Timestamp('2006-09-30 00:00:00')]},
 1907: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1924: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1934: {'start_dates': [Timestamp('2002-06-16 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1951: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1953: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1960: {'start_dates': [Timestamp('2012-12-15 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1961: {'start_dates': [Timestamp('2012-12-15 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1964: {'start_dates': [Timestamp('2013-02-12 00:00:00')],
  'end_dates': [Timestamp('2024-03-12 00:00:00')]},
 1965: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 1976: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1980: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 1984: {'start_dates': [Timestamp('2004-08-12 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2007: {'start_dates': [Timestamp('2004-07-11 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2011: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2017: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2024: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2028: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2044: {'start_dates': [Timestamp('2003-09-06 00:00:00')],
  'end_dates': [Timestamp('2024-03-10 00:00:00')]},
 2048: {'start_dates': [Timestamp('2003-02-26 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2051: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2067: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2076: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2091: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2099: {'start_dates': [Timestamp('2001-11-27 00:00:00')],
  'end_dates': [Timestamp('2019-09-30 00:00:00')]},
 2101: {'start_dates': [Timestamp('2001-11-27 00:00:00')],
  'end_dates': [Timestamp('2019-09-30 00:00:00')]},
 2109: {'start_dates': [Timestamp('2003-09-06 00:00:00')],
  'end_dates': [Timestamp('2024-03-10 00:00:00')]},
 2111: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2126: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2127: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2138: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2140: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2141: {'start_dates': [Timestamp('2012-12-15 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2153: {'start_dates': [Timestamp('2013-03-15 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 216: {'start_dates': [Timestamp('2012-12-15 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 217: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2175: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2180: {'start_dates': [Timestamp('2003-09-06 00:00:00')],
  'end_dates': [Timestamp('2024-03-10 00:00:00')]},
 2188: {'start_dates': [Timestamp('2005-10-02 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2190: {'start_dates': [Timestamp('2004-11-18 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2193: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2197: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2203: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2222: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2235: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2261: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2262: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2280: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2281: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2299: {'start_dates': [Timestamp('2004-10-07 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2303: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2305: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 231: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2324: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2327: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2338: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 234: {'start_dates': [Timestamp('2003-09-06 00:00:00')],
  'end_dates': [Timestamp('2024-03-10 00:00:00')]},
 2345: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2346: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2348: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2350: {'start_dates': [Timestamp('2006-08-09 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2351: {'start_dates': [Timestamp('2010-01-02 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2362: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2366: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2380: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2430: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2431: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2441: {'start_dates': [Timestamp('2008-10-04 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2449: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2461: {'start_dates': [Timestamp('2011-07-03 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2463: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-10-01 00:00:00')]},
 2470: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2483: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2487: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2495: {'start_dates': [Timestamp('2006-05-10 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},
 2496: {'start_dates': [Timestamp('2002-04-22 00:00:00')],
  'end_dates': [Timestamp('2020-09-30 00:00:00')]},

In [ ]:
period = 'validation'

sample_train = pd.read_csv(f'./data/sample_{period}.txt', header=None).squeeze().tolist()

PATH_PLOT = PATH_RESOPS / 'time_series' / 'plots' / period
PATH_PLOT.mkdir(parents=True, exist_ok=True)

for ID in tqdm(sample_train):
    df = xr.open_dataset(PATH_RESOPS / 'time_series' / f'{ID}.nc').to_pandas()
    df = df[cfg.dynamic_inputs + cfg.target_variables]

    fig, ax = plt.subplots(figsize=(12, 4))
    df.plot(ax=ax, lw=1)
    ax.set(title=ID,
           xlim=(df.index.min(), df.index.max()));
    for x in periods_da.sel(id=str(ID), date='start').to_numpy():
        plt.axvline(x, ls='-', lw=.5, color='k', zorder=0)
    plt.savefig(PATH_PLOT / f'{ID}.jpg', dpi=300, bbox_inches='tight')

***

In [94]:
from neuralhydrology.datasetzoo import BaseDataset

In [96]:
BaseDataset(cfg, is_train=True, period='train')

NotImplementedError: